default:
    @just --list

arch := if `uname -m` == "x86_64" {
        "-D__TARGET_ARCH_x86"
    } else if  `uname -m`=="aarch64" { 
        "-D__TARGET_ARCH_arm64"
    } else {
        ""
    }
clang_flags :="-g -O2 -mcpu=v2" +" " + arch +" " + "-Wunused-command-line-argument -target bpf"
ebpf:
    clang {{ clang_flags }} -I./ebpf/ \
        -c ./ebpf/swarmor.ebpf.c  \
        -o ./target/swarmor.o 

build:
    go build -o target/swarmor ./cmd/main.go
run: build
    sudo ./target/swarmor